### ISSUE TITLE
A problem with accented characters.

### ISSUE THREAD

**Issue by ghost** [nodeca/unhomoglyph#1]
résumé são -> résurné são

**Comment by puzrin** [comment]
What is the problem with it?

**Comment by ghost** [comment]
Maybe I don't understand the idea of your library, but it looks weird for me, that _résumé_ moves to _résurné_. m->rn

**Comment by puzrin** [comment]
Idea is very simple. Imagine that you have visually similar strings, and wish so understand are they similar or not. If you pass both via this library, similar string will give you equal result.

Note, that only equality make sense. Result should not be human readable or have correct grammar. Library output is intended only for equality check.

As you see, "m" and "r + n" looks the same. So, outputs are equal, profit :).

**Comment by puzrin** [comment]
`homoglyph('m') === homoglyph('r' + 'n')`
