### ISSUE TITLE
[React Native] Unterminated string constant in unhomoglyph/data.json

### ISSUE THREAD

**Issue by annie-elequin** [nodeca/unhomoglyph#2]
![image](https://user-images.githubusercontent.com/20155539/60366718-fc242880-99b1-11e9-9ff1-2f61d79df353.png)

I get this error when using matrix-js-sdk with React Native Expo and I try to **publish** the project. (I can run the project in Simulator without publishing)

### Expected behavior
Expo should successfully publish the app to the user's account.

### To Reproduce
1. Create a new Expo project with `expo init`.
2. `yarn add matrix-js-sdk`.
3. Follow steps in [this article](https://annie-elequin.proseful.com/using-the-matrix-js-sdk-work-with-expo) to get `matrix-js-sdk` working.
4. Start package manager with `expo start` and in another terminal, run `expo publish`.

### Environment
MacOS 10.14.5
iOS Simulator XR 12.1
Node 10.16.0
Expo CLI 2.21.1 (SDK 33)
Matrix JS SDK 2.0.1

### Other Notes
I tried removing line 159 (the original error line) from unhomoglyph/data.json, which didn't work, and subsequently removed every line after that - it ended up just changing the error line to the last line in the file (154 in the screenshot).

**Comment by puzrin** [comment]
Sorry, i can not debug third party tools for you. That seems out of project scope.

**Comment by annie-elequin** [comment]
For reference, @puzrin this is also happening with Metro Bundler, with normal React Native. So there's something about unhomoglyph that minifying/bundling doesn't play nice with.

**Comment by puzrin** [comment]
May be those don't play well with utf-8 content. Sorry, but i really have no possibility to investigate thirt-party tools.

You could try to force minifier use ascii encoder, may be that helps. Or clone repo, recode json file to ascii and check what happens.
