### ISSUE TITLE
Support for Hermes Engine

### ISSUE THREAD

**Issue by djschilling** [nodeca/unhomoglyph#7]
I run in the same issue described here: https://github.com/nodeca/unhomoglyph/issues/2

I investigated a little bit further.
The problem seems to be hermes currently not supporting some unicode chars.
I opened an issue for this at the hermes repo: https://github.com/facebook/hermes/issues/235

Problem is i think it will take a while until it is fixed on their side.
So my suggestion would be to remove these 4 Unicode characters from data.json until it works in hermes.

**Comment by puzrin** [comment]
@djschilling did you tried to force your app builder use asscii only?

For example, with terser: https://github.com/markdown-it/markdown-it/blob/master/Makefile#L93 see `ascii_only=true`

Usually problem is in bad page charset or default server encoding. Forcing src to ascii avoid badly encoded characters to appear.

And IMO that's not related to this package.

**Comment by djschilling** [comment]
For react-native the bundler metro is used. there i can find no option to force asscii.

The issue got excepted in the hermes repo, but i guess it will take some time until i can use it from there.

So you are right it is not really a bug of this repo, but you could rather easily help to make life easier for users of this repo.

I think there are two options for this repo to help

1. Remove the two Unicode chars \u2028 and \u2029.
2. Change the data.json directly to ascii

**Comment by puzrin** [comment]
It's not good for maintainability to uglify sources. It sounds reasonable to ascii-fy 2 chars.

But is this so urgent? May be hermes will release fix soon?

**Comment by djschilling** [comment]
The problem is that my use of hermes is bind to the react-native version i use and these come out not so often.

**Comment by puzrin** [comment]
Ok. Only `\u2028` and `\u2029` need escaping?

**Comment by djschilling** [comment]
yes

**Comment by puzrin** [comment]
Published 1.0.6.

Thanks for your help!
